// Code generated by packages/contracts/permission/generate-frontend.ts; DO NOT EDIT.

export const PERMISSION = {
  ORG_READ: 'org:read',
  ORG_MANAGE: 'org:manage',
  ORG_ADMIN: 'org:admin',
  BUDGET_READ: 'budget:read',
  BUDGET_MANAGE: 'budget:manage',
  BUDGET_APPROVE: 'budget:approve',
  BUDGET_ADMIN: 'budget:admin',
  MODEL_READ: 'model:read',
  MODEL_MANAGE: 'model:manage',
  KEYS_READ: 'keys:read',
  KEYS_MANAGE: 'keys:manage',
  KEYS_ADMIN: 'keys:admin',
  BILLING_READ: 'billing:read',
  BILLING_MANAGE: 'billing:manage',
  DASHBOARD_READ: 'dashboard:read',
  AUDIT_READ: 'audit:read',
  SELF_KEYS: 'self:keys',
  SELF_APPROVAL: 'self:approval',
  API_CALL: 'api:call',
  PLATFORM_ADMIN: 'platform:admin',
  PLATFORM_MANAGE: 'platform:manage',
  PLATFORM_READ: 'platform:read',
} as const

export type PermissionKey = (typeof PERMISSION)[keyof typeof PERMISSION]
