// Code generated by packages/contracts/permission/generate-frontend.ts; DO NOT EDIT.

export const PERMISSION = {
  ORG_READ: 'org:read',
  ORG_DATASOURCE: 'org:datasource',
  ORG_STRUCTURE: 'org:structure',
  ORG_ROLES: 'org:roles',
  ORG_MEMBERS: 'org:members',
  BUDGET_READ: 'budget:read',
  BUDGET_ALLOCATE: 'budget:allocate',
  BUDGET_APPROVE: 'budget:approve',
  BUDGET_POLICY: 'budget:policy',
  MODEL_READ: 'model:read',
  MODEL_MANAGE: 'model:manage',
  MODEL_WHITELIST: 'model:whitelist',
  KEYS_READ: 'keys:read',
  KEYS_ADMIN: 'keys:admin',
  KEYS_PROVIDER: 'keys:provider',
  SELF_KEYS: 'self:keys',
  SELF_APPROVAL: 'self:approval',
  DASHBOARD_COST: 'dashboard:cost',
  DASHBOARD_USAGE: 'dashboard:usage',
  AUDIT_READ: 'audit:read',
  API_CALL: 'api:call',
  BILLING_READ: 'billing:read',
  BILLING_RECHARGE: 'billing:recharge',
  PLATFORM_MANAGE: 'platform:manage',
} as const

export type PermissionKey = (typeof PERMISSION)[keyof typeof PERMISSION]
