import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const permissionRoot = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(permissionRoot, '../../..')
const manifestPath = join(permissionRoot, 'manifest.json')
const outPath = join(repoRoot, 'apps/frontend/src/lib/permission-keys.ts')

type Manifest = {
  capabilities: string[]
}

function tsConstName(cap: string): string {
  return cap
    .split(':')
    .flatMap((part) => part.split('_'))
    .map((seg) => seg.toUpperCase())
    .join('_')
}

const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as Manifest
const lines = [
  '// Code generated by packages/contracts/permission/generate-frontend.ts; DO NOT EDIT.',
  '',
  'export const PERMISSION = {',
  ...manifest.capabilities.map((cap) => `  ${tsConstName(cap)}: '${cap}',`),
  '} as const',
  '',
  'export type PermissionKey = (typeof PERMISSION)[keyof typeof PERMISSION]',
  '',
]

writeFileSync(outPath, lines.join('\n'))
