package permission

// Code generated by packages/contracts/permission/generate-backend.go; DO NOT EDIT.

const (
	OrgRead         = "org:read"
	OrgDatasource   = "org:datasource"
	OrgStructure    = "org:structure"
	OrgRoles        = "org:roles"
	OrgMembers      = "org:members"
	BudgetRead      = "budget:read"
	BudgetAllocate  = "budget:allocate"
	BudgetApprove   = "budget:approve"
	BudgetPolicy    = "budget:policy"
	ModelRead       = "model:read"
	ModelManage     = "model:manage"
	ModelWhitelist  = "model:whitelist"
	KeysRead        = "keys:read"
	KeysAdmin       = "keys:admin"
	KeysProvider    = "keys:provider"
	SelfKeys        = "self:keys"
	SelfApproval    = "self:approval"
	DashboardCost   = "dashboard:cost"
	DashboardUsage  = "dashboard:usage"
	AuditRead       = "audit:read"
	ApiCall         = "api:call"
	BillingRead     = "billing:read"
	BillingRecharge = "billing:recharge"
)

var AllPermissions = []string{
	OrgRead,
	OrgDatasource,
	OrgStructure,
	OrgRoles,
	OrgMembers,
	BudgetRead,
	BudgetAllocate,
	BudgetApprove,
	BudgetPolicy,
	ModelRead,
	ModelManage,
	ModelWhitelist,
	KeysRead,
	KeysAdmin,
	KeysProvider,
	SelfKeys,
	SelfApproval,
	DashboardCost,
	DashboardUsage,
	AuditRead,
	ApiCall,
	BillingRead,
	BillingRecharge,
}

var PermissionIDMap = map[string]string{
	"p-1":  OrgStructure,
	"p-10": AuditRead,
	"p-11": ApiCall,
	"p-12": BudgetRead,
	"p-13": BudgetPolicy,
	"p-14": ModelManage,
	"p-15": KeysAdmin,
	"p-16": KeysProvider,
	"p-17": SelfKeys,
	"p-18": SelfApproval,
	"p-19": OrgRead,
	"p-2":  OrgMembers,
	"p-20": KeysRead,
	"p-21": ModelRead,
	"p-22": BillingRead,
	"p-23": BillingRecharge,
	"p-3":  OrgRoles,
	"p-4":  OrgDatasource,
	"p-5":  BudgetAllocate,
	"p-6":  BudgetApprove,
	"p-7":  ModelWhitelist,
	"p-8":  DashboardCost,
	"p-9":  DashboardUsage,
}
