package grants

// Code generated by packages/contracts/permission/generate-backend.go; DO NOT EDIT.

const (
	OrgRead        = "org:read"
	OrgManage      = "org:manage"
	OrgAdmin       = "org:admin"
	BudgetRead     = "budget:read"
	BudgetManage   = "budget:manage"
	BudgetApprove  = "budget:approve"
	BudgetAdmin    = "budget:admin"
	ModelRead      = "model:read"
	ModelManage    = "model:manage"
	KeysRead       = "keys:read"
	KeysManage     = "keys:manage"
	KeysAdmin      = "keys:admin"
	BillingRead    = "billing:read"
	BillingManage  = "billing:manage"
	DashboardRead  = "dashboard:read"
	AuditRead      = "audit:read"
	SelfKeys       = "self:keys"
	SelfApproval   = "self:approval"
	APICall        = "api:call"
	PlatformAdmin  = "platform:admin"
	PlatformManage = "platform:manage"
	PlatformRead   = "platform:read"
)

// CompanyPermissions are tenant-assignable permissions. * expands to this set only.
var CompanyPermissions = []string{
	OrgRead,
	OrgManage,
	OrgAdmin,
	BudgetRead,
	BudgetManage,
	BudgetApprove,
	BudgetAdmin,
	ModelRead,
	ModelManage,
	KeysRead,
	KeysManage,
	KeysAdmin,
	BillingRead,
	BillingManage,
	DashboardRead,
	AuditRead,
	SelfKeys,
	SelfApproval,
	APICall,
}

// AllPermissions includes both company and platform permissions.
var AllPermissions = []string{
	OrgRead,
	OrgManage,
	OrgAdmin,
	BudgetRead,
	BudgetManage,
	BudgetApprove,
	BudgetAdmin,
	ModelRead,
	ModelManage,
	KeysRead,
	KeysManage,
	KeysAdmin,
	BillingRead,
	BillingManage,
	DashboardRead,
	AuditRead,
	SelfKeys,
	SelfApproval,
	APICall,
	PlatformAdmin,
	PlatformManage,
	PlatformRead,
}

// PermissionIDMap maps stable permission IDs (p-1, p-2 ...) to capability strings.
var PermissionIDMap = map[string]string{
	"p-1":  OrgAdmin,
	"p-10": KeysAdmin,
	"p-11": KeysManage,
	"p-12": KeysRead,
	"p-13": BillingManage,
	"p-14": BillingRead,
	"p-15": DashboardRead,
	"p-16": AuditRead,
	"p-17": SelfKeys,
	"p-18": SelfApproval,
	"p-19": APICall,
	"p-2":  OrgManage,
	"p-3":  OrgRead,
	"p-4":  BudgetAdmin,
	"p-5":  BudgetManage,
	"p-6":  BudgetApprove,
	"p-7":  BudgetRead,
	"p-8":  ModelManage,
	"p-9":  ModelRead,
}
