package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type manifest struct {
	Capabilities    []string          `json:"capabilities"`
	PermissionIDMap map[string]string `json:"permissionIdMap"`
}

func main() {
	manifestPath := filepath.Join("internal", "infra", "permission", "manifest.json")
	outPath := filepath.Join("internal", "infra", "permission", "keys.go")

	raw, err := os.ReadFile(manifestPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read manifest: %v\n", err)
		os.Exit(1)
	}
	var m manifest
	if err := json.Unmarshal(raw, &m); err != nil {
		fmt.Fprintf(os.Stderr, "parse manifest: %v\n", err)
		os.Exit(1)
	}

	var b strings.Builder
	b.WriteString("package permission\n\n")
	b.WriteString("// Code generated by genkeys; DO NOT EDIT.\n\n")
	b.WriteString("const (\n")
	for _, cap := range m.Capabilities {
		b.WriteString(fmt.Sprintf("\t%s = %q\n", goConstName(cap), cap))
	}
	b.WriteString(")\n\n")
	b.WriteString("var AllPermissions = []string{\n")
	for _, cap := range m.Capabilities {
		b.WriteString(fmt.Sprintf("\t%s,\n", goConstName(cap)))
	}
	b.WriteString("}\n\n")
	b.WriteString("var PermissionIDMap = map[string]string{\n")
	ids := make([]string, 0, len(m.PermissionIDMap))
	for id := range m.PermissionIDMap {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		cap := m.PermissionIDMap[id]
		b.WriteString(fmt.Sprintf("\t%q: %s,\n", id, goConstName(cap)))
	}
	b.WriteString("}\n")

	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write keys: %v\n", err)
		os.Exit(1)
	}
}

func goConstName(cap string) string {
	parts := strings.Split(cap, ":")
	var words []string
	for _, part := range parts {
		for _, seg := range strings.Split(part, "_") {
			if seg == "" {
				continue
			}
			words = append(words, strings.ToUpper(seg[:1])+seg[1:])
		}
	}
	return strings.Join(words, "")
}
