import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const manifestPath = join(root, 'apps/backend/internal/infra/permission/manifest.json')
const outPath = join(root, 'apps/frontend/src/lib/permission-keys.ts')

type Manifest = {
  capabilities: string[]
}

function tsConstName(cap: string): string {
  return cap
    .split(':')
    .flatMap((part) => part.split('_'))
    .map((seg) => seg.toUpperCase())
    .join('_')
}

const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as Manifest
const lines = [
  '// Code generated by scripts/generate-permissions.ts; DO NOT EDIT.',
  '',
  'export const PERMISSION = {',
  ...manifest.capabilities.map((cap) => `  ${tsConstName(cap)}: '${cap}',`),
  '} as const',
  '',
  'export type PermissionKey = (typeof PERMISSION)[keyof typeof PERMISSION]',
  '',
]

writeFileSync(outPath, lines.join('\n'))
