root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server ./cmd/server"
bin = "./tmp/server"
full_bin = "./tmp/server"
include_ext = ["go"]
exclude_dir = ["tmp", "bin", "uploads"]
delay = 1000

[misc]
clean_on_exit = true
